import { PlotState, CropType, FoodType, Season, AnimalProductType, SupplyType, Recipe, ToolType, PetType, PetRarity } from "./types";

export const INITIAL_FARM_SIZE = 9;
export const INITIAL_GREENHOUSE_SIZE = 6;
export const GREENHOUSE_PRICE = 30;
export const RANCH_PRICE = 50;
export const PET_PULL_COST = {
    single: 1,
    multi: 10,
};


// Language-independent data
export const CROP_DATA = {
    carrot: { icon: '🥕', growthTime: 10000, sellPrice: 15, seedPrice: 5, seasons: ['Spring', 'Autumn'], xp: 5 },
    tomato: { icon: '🍅', growthTime: 20000, sellPrice: 35, seedPrice: 10, seasons: ['Summer'], xp: 10 },
    potato: { icon: '🥔', growthTime: 30000, sellPrice: 50, seedPrice: 20, seasons: ['Autumn'], xp: 15 },
    cucumber: { icon: '🥒', growthTime: 7000, sellPrice: 10, seedPrice: 3, seasons: ['Summer'], xp: 3 },
    broccoli: { icon: '🥦', growthTime: 8000, sellPrice: 12, seedPrice: 4, seasons: ['Spring', 'Autumn'], xp: 4 },
    strawberry: { icon: '🍓', growthTime: 12000, sellPrice: 20, seedPrice: 7, seasons: ['Spring'], xp: 7 },
    corn: { icon: '🌽', growthTime: 15000, sellPrice: 25, seedPrice: 8, seasons: ['Summer'], xp: 8 },
    bell_pepper: { icon: '🫑', growthTime: 22000, sellPrice: 40, seedPrice: 15, seasons: ['Summer', 'Autumn'], xp: 12 },
    eggplant: { icon: '🍆', growthTime: 25000, sellPrice: 45, seedPrice: 18, seasons: ['Autumn'], xp: 14 },
    watermelon: { icon: '🍉', growthTime: 40000, sellPrice: 80, seedPrice: 30, seasons: ['Summer'], xp: 25 },
    stardust_sprout: { icon: '✨', growthTime: 60000, sellPrice: 500, seedPrice: 100, seasons: ['Spring', 'Summer', 'Autumn', 'Winter'], xp: 100 },
} as const;

export const FOOD_DATA = {
    bread: { icon: '🍞', price: 25, hungerRestore: 15 },
    salad: { icon: '🥗', price: 50, hungerRestore: 30 },
    sandwich: { icon: '🥪', price: 75, hungerRestore: 45 },
    pizza: { icon: '🍕', price: 120, hungerRestore: 70 },
    steak: { icon: '🥩', price: 150, hungerRestore: 90 },
    strawberry_cake: { icon: '🍰', price: 85, hungerRestore: 55, seasonality: 'Spring' },
    bibimbap: { icon: '🍚', price: 100, hungerRestore: 60, seasonality: 'Spring' },
    cold_noodles: { icon: '🍜', price: 120, hungerRestore: 70, seasonality: 'Summer' },
    shaved_ice: { icon: '🍧', price: 130, hungerRestore: 75, seasonality: 'Summer' },
    samgyetang: { icon: '🍲', price: 160, hungerRestore: 95, seasonality: 'Summer' },
    roasted_sweet_potato: { icon: '🍠', price: 70, hungerRestore: 40, seasonality: 'Autumn' },
    persimmon: { icon: '🍊', price: 45, hungerRestore: 28, seasonality: 'Autumn' },
    jjinppang: { icon: '🥟', price: 80, hungerRestore: 50, seasonality: 'Winter' },
    udon: { icon: '🍜', price: 110, hungerRestore: 65, seasonality: 'Winter' },
    veggie_stir_fry: { icon: '🥘', price: 100, hungerRestore: 50 },
    omelette: { icon: '🍳', price: 150, hungerRestore: 75 },
    truffle_pasta: { icon: '🍝', price: 500, hungerRestore: 100 },
} as const;

export const ANIMAL_DATA = {
    chicken: { icon: '🐔', price: 200 },
    cow: { icon: '🐮', price: 1000 },
    pig: { icon: '🐷', price: 1500 },
} as const;

export const ANIMAL_PRODUCT_DATA = {
    egg: { icon: '🥚', sellPrice: 25 },
    milk: { icon: '🥛', sellPrice: 50 },
    truffle: { icon: '🍄', sellPrice: 250 },
    golden_egg: { icon: '🌟', sellPrice: 1000 },
} as const;

export const SUPPLY_DATA = {
    feed: { icon: '🌾', price: 10 },
    golden_fertilizer: { icon: '✨', price: 250 },
    pet_biscuit: { icon: '🦴', price: 500 },
} as const;

export const TOOL_DATA: Record<ToolType, { icon: string; price: number }> = {
    wateringCan: { icon: '💧', price: 150 },
    sprinkler: { icon: '💦', price: 2000 },
} as const;

export const PET_DATA: Record<PetType, { icon: string; rarity: PetRarity; passive: any }> = {
    farm_dog: { icon: '🐶', rarity: 'common', passive: { findFeedChance: 0.1 } },
    calico_cat: { icon: '🐱', rarity: 'rare', passive: { moneyBonus: 0.05 } },
    wise_owl: { icon: '🦉', rarity: 'epic', passive: { xpBonus: 0.10 } },
    golden_goose: { icon: '🦆', rarity: 'epic', passive: { goldenEggChance: 0.05 } },
    mini_dragon: { icon: '🐲', rarity: 'legendary', passive: { growthSpeedBonus: 0.15 } },
};

export const PET_RARITY_CHANCES: Record<PetRarity, number> = {
    common: 0.60,
    rare: 0.25,
    epic: 0.12,
    legendary: 0.03,
};


export const RECIPE_DATA: Record<'veggie_stir_fry' | 'omelette' | 'truffle_pasta', Recipe> = {
    veggie_stir_fry: {
        result: { type: 'food', key: 'veggie_stir_fry', quantity: 1 },
        ingredients: [
            { type: 'rawCrop', key: 'carrot', quantity: 1 },
            { type: 'rawCrop', key: 'broccoli', quantity: 1 },
        ]
    },
    omelette: {
        result: { type: 'food', key: 'omelette', quantity: 1 },
        ingredients: [
            { type: 'animalProduct', key: 'egg', quantity: 2 },
            { type: 'animalProduct', key: 'milk', quantity: 1 },
        ]
    },
    truffle_pasta: {
        result: { type: 'food', key: 'truffle_pasta', quantity: 1 },
        ingredients: [
            { type: 'animalProduct', key: 'truffle', quantity: 1 },
            { type: 'food', key: 'bread', quantity: 1 },
        ]
    },
} as const;


export const XP_FOR_NEXT_LEVEL = [0, 100, 250, 500, 1000, 2000, 4000, 8000, 15000, 30000, 50000, 100000]; // XP needed to reach level (index + 1)

export const ACHIEVEMENT_DATA = {
    // Money Category
    money1: { icon: '💰', requires: { stat: 'totalGoldEarned', value: 500 }, category: 'Money', tier: 1 },
    money2: { icon: '🤑', requires: { stat: 'totalGoldEarned', value: 5000 }, category: 'Money', tier: 2 },
    money3: { icon: '🪙', requires: { stat: 'totalGoldEarned', value: 25000 }, category: 'Money', tier: 3 },
    money4: { icon: '🏦', requires: { stat: 'totalGoldEarned', value: 100000 }, category: 'Money', tier: 4 },

    // Harvest Category
    harvest1: { icon: '🎉', requires: { stat: 'totalCropsHarvested', value: 1 }, category: 'Harvest', tier: 1 },
    harvest2: { icon: '🧺', requires: { stat: 'totalCropsHarvested', value: 50 }, category: 'Harvest', tier: 2 },
    harvest3: { icon: '🚜', requires: { stat: 'totalCropsHarvested', value: 250 }, category: 'Harvest', tier: 3 },
    harvest4: { icon: '🌾', requires: { stat: 'totalCropsHarvested', value: 1000 }, category: 'Harvest', tier: 4 },
    
    // Level Category
    level1: { icon: '🎓', requires: { stat: 'level', value: 5 }, category: 'Level', tier: 1 },
    level2: { icon: '🌟', requires: { stat: 'level', value: 10 }, category: 'Level', tier: 2 },
    level3: { icon: '🚀', requires: { stat: 'level', value: 20 }, category: 'Level', tier: 3 },

    // Farm Expansion Category
    expand1: { icon: '🏞️', requires: { stat: 'farmPlots', value: INITIAL_FARM_SIZE + 1 }, category: 'Expansion', tier: 1 },
    expand2: { icon: '🌄', requires: { stat: 'farmPlots', value: 15 }, category: 'Expansion', tier: 2 },
    expand3: { icon: '🌍', requires: { stat: 'farmPlots', value: 25 }, category: 'Expansion', tier: 3 },
    
    // Greenhouse Category
    greenhouse1: { icon: '🏡', requires: { stat: 'hasGreenhouse', value: true }, category: 'Greenhouse', tier: 1 },
    greenhouse2: { icon: '🏡➕', requires: { stat: 'greenhousePlots', value: 10 }, category: 'Greenhouse', tier: 2 },
    greenhouse3: { icon: '🏡🌳', requires: { stat: 'greenhousePlots', value: 20 }, category: 'Greenhouse', tier: 3 },

    // Animal Husbandry
    buildBarn1: { icon: '목장', requires: { stat: 'hasBarn', value: true }, category: 'Husbandry', tier: 1 },
    buyChicken1: { icon: '🐔', requires: { stat: 'totalAnimals', value: 1 }, category: 'Husbandry', tier: 2 },
    collectEgg1: { icon: '🥚', requires: { stat: 'totalProductsCollected', value: 1 }, category: 'Husbandry', tier: 3 },
    buyCow1: { icon: '🐮', requires: { stat: 'totalAnimals', value: 2 }, category: 'Husbandry', tier: 4 }, // Example: requires more than 1 animal
    collectMilk1: { icon: '🥛', requires: { stat: 'totalProductsCollected', value: 5 }, category: 'Husbandry', tier: 5 },
    buyPig1: { icon: '🐷', requires: { stat: 'totalAnimals', value: 3 }, category: 'Husbandry', tier: 6 },
    collectTruffle1: { icon: '🍄', requires: { stat: 'totalProductsCollected', value: 10 }, category: 'Husbandry', tier: 7 },


    // Seasonal Master Category
    seasonalSpring: { icon: '🌸', requires: { stat: 'springCropsHarvested', value: 25 }, category: 'Seasonal', tier: 1 },
    seasonalSummer: { icon: '🌻', requires: { stat: 'summerCropsHarvested', value: 25 }, category: 'Seasonal', tier: 2 },
    seasonalAutumn: { icon: '🍁', requires: { stat: 'autumnCropsHarvested', value: 25 }, category: 'Seasonal', tier: 3 },
    seasonalWinter: { icon: '❄️', requires: { stat: 'winterCropsHarvested', value: 25 }, category: 'Seasonal', tier: 4 },

    // Beta Tester Category
    foodie1: { icon: '😋', requires: { stat: 'foodEaten', value: 10 }, category: 'Beta', tier: 1 },
    foodie2: { icon: '🍽️', requires: { stat: 'foodEaten', value: 50 }, category: 'Beta', tier: 2 },
} as const;


// All translatable strings
export const translations = {
    en: {
        title: "My Little Farm",
        enterFarmNamePlaceholder: "Enter Farm Name",
        startGame: "🎮 Start Game",
        betaTest: "🧪 Beta Test",
        settings: "⚙️ Settings",
        language: "Language",
        aspectRatio: "Aspect Ratio",
        default: "Default",
        widescreen: "16:9",
        myInventory: "My Inventory",
        visitShop: "🛍️ Visit Shop",
        seedShop: "Seed Shop",
        foodShop: "Food Shop",
        expandFarm: "🏞️ Expand Farm",
        carrot: "Carrot",
        tomato: "Tomato",
        potato: "Potato",
        cucumber: "Cucumber",
        broccoli: "Broccoli",
        strawberry: "Strawberry",
        corn: "Corn",
        bell_pepper: "Bell Pepper",
        eggplant: "Eggplant",
        watermelon: "Watermelon",
        stardust_sprout: "Stardust Sprout",
        bread: "Bread",
        salad: "Salad",
        sandwich: "Sandwich",
        pizza: "Pizza",
        steak: "Steak",
        strawberry_cake: "Strawberry Cake",
        bibimbap: "Spring Greens Bibimbap",
        cold_noodles: "Cold Noodles",
        shaved_ice: "Shaved Ice",
        samgyetang: "Ginseng Chicken Soup",
        roasted_sweet_potato: "Roasted Sweet Potato",
        persimmon: "Persimmon",
        jjinppang: "Jjinppang",
        udon: "Udon",
        veggie_stir_fry: "Veggie Stir-fry",
        omelette: "Omelette",
        truffle_pasta: "Truffle Pasta",
        sound: "Sound",
        musicOn: "Music On 🔊",
        musicOff: "Music Off 🔇",
        wateringCan: "Watering Can",
        wateringCanDescription: "When planting a seed, its initial growth time is reduced by 50%.",
        sprinkler: "Sprinkler",
        sprinklerDescription: "Automatically waters all farm and greenhouse plots every morning.",
        golden_fertilizer: "Golden Fertilizer",
        golden_fertilizer_desc: "Guarantees a large-sized crop when used on a growing plant.",
        pet_biscuit: "Pet Biscuit",
        pet_biscuit_desc: "A tasty treat used to attract new pets.",
        feed: "Feed",
        feed_desc: "Food for your ranch animals. Keep them happy and productive!",
        tools: "🛠️ Tools",
        owned: "Owned",
        seeds: "🌱 Seeds",
        food: "🍔 Food",
        eat: "🍽️ Eat",
        sell: "💰 Sell",
        sellAll: "💰💰 Sell All",
        harvestAll: "🔪 Harvest All",
        hunger: "Hunger",
        score: "Score",
        harvested: "Harvested!",
        keepAsFood: "Keep as Food",
        buy: "🛒 Buy",
        total: "Total",
        weather: "Weather",
        sunny: "Sunny",
        rainy: "Rainy",
        cloudy: "Cloudy",
        heavyRain: "Heavy Rain",
        heatwave: "Heatwave",
        typhoon: "Typhoon",
        blizzard: "Blizzard",
        heavyRainAlertTitle: "Heavy Rain Alert!",
        heatwaveAlertTitle: "Uncommon Heatwave!",
        typhoonAlertTitle: "Rare Typhoon!",
        blizzardAlertTitle: "Very Rare Blizzard!",
        heavyRainAlertBody: "Heavy rain has caused crop prices to soar by 50%!",
        heatwaveAlertBody: "Crops grow faster in the heat, but you get hungry quicker!",
        typhoonAlertBody: "Strong winds have destroyed some of your crops!",
        blizzardAlertBody: "A blizzard has halted all crop growth!",
        disasterChance: "Disaster Chance",
        money: "Money",
        moneyTooltip: "This is your current gold. Use it to buy seeds, food, and expand your farm.",
        scoreTooltip: "This is your score. It increases as you sell crops and perform other actions.",
        weatherTooltip: "This is the current weather. It can affect your crops and game events.",
        disasterChanceTooltip: "This is the chance of a natural disaster occurring with the next weather change.",
        wateringCanTooltip: "You own a watering can! New plants will be automatically watered, reducing their growth time by 50%.",
        hungerTooltip: "This is your hunger level (Beta Mode). Eat food to restore it. If it reaches zero, you will be penalized.",
        day: "Day",
        dayTooltip: "This is the current date. Weather and prices change at the start of each new day.",
        nextDisasterChanceLabel: "Next Chance",
        pricesRefreshIn: "Prices refresh in",
        year: "Year",
        month: "Month",
        spring: "Spring",
        summer: "Summer",
        autumn: "Autumn",
        winter: "Winter",
        greenhouse: "Greenhouse",
        greenhouseDescription: "Allows you to grow any crop, regardless of the season. A Winter essential!",
        viewGreenhouse: "🌿 Greenhouse",
        greenhouseSeedShop: "Greenhouse Seed Shop",
        expandGreenhouse: "🌿 Expand Greenhouse",
        chooseStartingSeason: "Choose Starting Season",
        level: "Level",
        xp: "XP",
        achievements: "🏆 Achievements",
        upgrades: "✨ Upgrades",
        newAchievementUnlocked: "New Achievement Unlocked!",
        achievement_money1_name: "Getting Started",
        achievement_money1_desc: "Earn a total of 500 gold.",
        achievement_money2_name: "Wealthy Farmer",
        achievement_money2_desc: "Earn a total of 5,000 gold.",
        achievement_money3_name: "Gold Hoarder",
        achievement_money3_desc: "Earn a total of 25,000 gold.",
        achievement_money4_name: "Farm Tycoon",
        achievement_money4_desc: "Earn a total of 100,000 gold.",
        achievement_harvest1_name: "First Harvest",
        achievement_harvest1_desc: "Successfully harvest your first crop.",
        achievement_harvest2_name: "Green Thumb",
        achievement_harvest2_desc: "Harvest a total of 50 crops.",
        achievement_harvest3_name: "Expert Harvester",
        achievement_harvest3_desc: "Harvest a total of 250 crops.",
        achievement_harvest4_name: "Master of the Land",
        achievement_harvest4_desc: "Harvest a total of 1,000 crops.",
        achievement_level1_name: "Novice Farmer",
        achievement_level1_desc: "Reach Level 5.",
        achievement_level2_name: "Skilled Farmer",
        achievement_level2_desc: "Reach Level 10.",
        achievement_level3_name: "Farming Legend",
        achievement_level3_desc: "Reach Level 20.",
        achievement_expand1_name: "Room to Grow",
        achievement_expand1_desc: "Expand your farm for the first time.",
        achievement_expand2_name: "Landowner",
        achievement_expand2_desc: "Own 15 farm plots.",
        achievement_expand3_name: "Agricultural Empire",
        achievement_expand3_desc: "Own 25 farm plots.",
        achievement_greenhouse1_name: "Four Seasons",
        achievement_greenhouse1_desc: "Build the Greenhouse.",
        achievement_greenhouse2_name: "Glass Gardener",
        achievement_greenhouse2_desc: "Own 10 greenhouse plots.",
        achievement_greenhouse3_name: "Controlled Environment",
        achievement_greenhouse3_desc: "Own 20 greenhouse plots.",
        achievement_seasonalSpring_name: "Spring Specialist",
        achievement_seasonalSpring_desc: "Harvest 25 Spring crops.",
        achievement_seasonalSummer_name: "Summer Specialist",
        achievement_seasonalSummer_desc: "Harvest 25 Summer crops.",
        achievement_seasonalAutumn_name: "Autumn Specialist",
        achievement_seasonalAutumn_desc: "Harvest 25 Autumn crops.",
        achievement_seasonalWinter_name: "Winter Specialist",
        achievement_seasonalWinter_desc: "Harvest 25 crops from the Greenhouse in Winter.",
        achievement_foodie1_name: "Foodie",
        achievement_foodie1_desc: "Eat 10 times in Beta Mode.",
        achievement_foodie2_name: "Gourmand",
        achievement_foodie2_desc: "Eat 50 times in Beta Mode.",
        achievement_buildBarn1_name: "Rancher's Beginning",
        achievement_buildBarn1_desc: "Build a ranch for your animals.",
        achievement_buyChicken1_name: "First Friend",
        achievement_buyChicken1_desc: "Buy your first chicken.",
        achievement_collectEgg1_name: "Egg Collector",
        achievement_collectEgg1_desc: "Collect your first egg.",
        achievement_buyCow1_name: "Moo-ver and Shaker",
        achievement_buyCow1_desc: "Buy your first cow.",
        achievement_collectMilk1_name: "Got Milk?",
        achievement_collectMilk1_desc: "Collect your first milk.",
        achievement_buyPig1_name: "Hog Wild",
        achievement_buyPig1_desc: "Buy your first pig.",
        achievement_collectTruffle1_name: "Treasure Hunter",
        achievement_collectTruffle1_desc: "Find your first truffle.",
        totalGoldEarned: "Total Gold Earned",
        cropsHarvested: "Crops Harvested",
        farmPlots: "Farm Plots",
        completed: "Completed",
        levelUpTitle: "Level Up!",
        levelUpMessage: "You've reached Level {level}!",
        levelUpReward: "Reward:",
        claimReward: "🎁 Claim",
        milestoneReward: "Milestone Reward",
        claimYourReward: "🎁 Claim Your Reward!",
        achievementsCompleted: "{count} / 5 Achievements Completed",
        allAchievementsCompleted: "All Achievements Completed!",
        comingSoon: "Coming Soon...",
        milestoneRewardTitle: "Huge Reward!",
        milestoneRewardMessage: "You've completed {count} achievements! Here is your reward:",
        andSeeds: "and {count} of each seed!",
        category_Money: "Wealth",
        category_Harvest: "Harvesting",
        category_Level: "Leveling Up",
        category_Expansion: "Expansion",
        category_Greenhouse: "Greenhouse",
        category_Seasonal: "Seasonal Master",
        category_Beta: "Beta Tester",
        category_Husbandry: "Husbandry",
        bulletinBoard: "📌 Bulletin Board",
        activeOrder: "Active Order",
        availableOrders: "Available Orders",
        accept: "✅ Accept",
        progress: "Progress",
        noOrdersAvailable: "No new orders today.",
        requester_restaurant: "Salty Squid Cafe",
        requester_mayor: "Mayor's Office",
        requester_school: "Village School",
        barn: "Ranch",
        buildBarn: "🏠 Build Ranch",
        buildBarnDescription: "Provides a home for your animals.",
        visitBarn: "🛖 Visit Ranch",
        animals: "🐾 Animals",
        supplies: "📦 Supplies",
        animalShop: "Animal Shop",
        suppliesShop: "Supplies Shop",
        chicken: "Chicken",
        cow: "Cow",
        pig: "Pig",
        egg: "Egg",
        milk: "Milk",
        truffle: "Truffle",
        golden_egg: "Golden Egg",
        products: "🥚 Products",
        feedAllAnimals: "🌾 Feed All Animals",
        returnToFarm: "🚜 Return to Farm",
        tradingPost: "⚖️ Trading Post",
        barter: "Barter",
        trade: "🤝 Trade",
        sellGoods: "💰 Sell Goods",
        kitchen: "🍳 Kitchen",
        cook: "👨‍🍳 Cook",
        ingredients: "Ingredients",
        crops: "🥕 Crops",
        moreActions: "🏘️ More Actions",
        petShelter: "🐾 Pet Shelter",
        adoptAPet: "Adopt a Pet",
        adopt: "Adopt",
        youAdopted: "You adopted a...",
        great: "Great!",
        rarity_common: "Common",
        rarity_rare: "Rare",
        rarity_epic: "Epic",
        rarity_legendary: "Legendary",
        farm_dog: "Farm Dog",
        farm_dog_desc: "A loyal companion. Has a 10% chance to find 1-3 free animal feed each morning.",
        calico_cat: "Calico Cat",
        calico_cat_desc: "Brings good fortune. Increases money from all sales by 5%.",
        wise_owl: "Wise Owl",
        wise_owl_desc: "A sage friend. Increases all XP gains by 10%.",
        golden_goose: "Golden Goose",
        golden_goose_desc: "A special bird. Has a 5% chance to lay a very valuable Golden Egg each day.",
        mini_dragon: "Mini-Dragon",
        mini_dragon_desc: "A mythical ally. Its fertile flames reduce all crop growth times by 15%.",
        petTooltip: "Your active pet. Click to manage your pets.",
        petGacha: "🐾 Pet Gacha",
        petHouse: "🏠 Pet House",
        pull1: "Pull 1",
        pull10: "Pull 10",
        pullCost: "Cost: {count} 🦴",
        guaranteedRare: "Guaranteed RARE or higher!",
        probabilities: "Probabilities",
        myPets: "My Pets",
        activeCompanion: "Active Companion",
        setActive: "Set Active",
        newFriends: "New Friends!",
        profile: "Profile",
        farmRecord: "Farm Record",
        stat_totalGoldEarned: "Total Gold Earned",
        stat_totalCropsHarvested: "Total Crops Harvested",
        stat_farmPlots: "Farm Plots",
        stat_greenhousePlots: "Greenhouse Plots",
        stat_hasGreenhouse: "Greenhouse Built",
        stat_springCrops: "Spring Harvests",
        stat_summerCrops: "Summer Harvests",
        stat_autumnCrops: "Autumn Harvests",
        stat_winterCrops: "Winter Harvests",
        stat_foodEaten: "Food Eaten",
        stat_hasBarn: "Ranch Built",
        stat_totalAnimals: "Total Animals",
        stat_totalProductsCollected: "Products Collected",
        willowSleeps: "The Willow sleeps...",
        listenToWillow: "Listen to the Willow",
        whisperingWillow: "The Whispering Willow",
        willowHums: "The ancient tree hums with latent energy...",
    },
    ko: {
        title: "나의 작은 농장",
        enterFarmNamePlaceholder: "농장 이름을 입력하세요",
        startGame: "🎮 게임 시작",
        betaTest: "🧪 베타 테스트",
        settings: "⚙️ 설정",
        language: "언어",
        aspectRatio: "화면 비율",
        default: "기본",
        widescreen: "16:9",
        myInventory: "내 인벤토리",
        visitShop: "🛍️ 상점 가기",
        seedShop: "씨앗 상점",
        foodShop: "음식 상점",
        expandFarm: "🏞️ 농장 확장",
        carrot: "당근",
        tomato: "토마토",
        potato: "감자",
        cucumber: "오이",
        broccoli: "브로콜리",
        strawberry: "딸기",
        corn: "옥수수",
        bell_pepper: "피망",
        eggplant: "가지",
        watermelon: "수박",
        stardust_sprout: "별빛 새싹",
        bread: "빵",
        salad: "샐러드",
        sandwich: "샌드위치",
        pizza: "피자",
        steak: "스테이크",
        strawberry_cake: "딸기 케이크",
        bibimbap: "봄나물 비빔밥",
        cold_noodles: "냉면",
        shaved_ice: "팥빙수",
        samgyetang: "삼계탕",
        roasted_sweet_potato: "군고구마",
        persimmon: "감",
        jjinppang: "찐빵",
        udon: "우동",
        veggie_stir_fry: "야채볶음",
        omelette: "오믈렛",
        truffle_pasta: "트러플 파스타",
        sound: "소리",
        musicOn: "음악 켜짐 🔊",
        musicOff: "음악 꺼짐 🔇",
        wateringCan: "물뿌리개",
        wateringCanDescription: "씨앗을 심을 때, 초기 성장 시간을 50% 단축시킵니다.",
        sprinkler: "스프링클러",
        sprinklerDescription: "매일 아침 농장과 비닐하우스의 모든 작물에 자동으로 물을 줍니다.",
        golden_fertilizer: "황금 비료",
        golden_fertilizer_desc: "자라나는 작물에 사용하면 큰 크기의 작물 수확을 보장합니다.",
        pet_biscuit: "펫 비스킷",
        pet_biscuit_desc: "새로운 펫을 유인하는 데 사용되는 맛있는 간식.",
        feed: "먹이",
        feed_desc: "목장 동물들을 위한 음식. 동물들을 행복하고 생산적으로 유지하세요!",
        tools: "🛠️ 도구",
        owned: "보유 중",
        seeds: "🌱 씨앗",
        food: "🍔 음식",
        eat: "🍽️ 먹기",
        sell: "💰 판매",
        sellAll: "💰💰 모두 판매",
        harvestAll: "🔪 모두 수확",
        hunger: "배고픔",
        score: "점수",
        harvested: "수확!",
        keepAsFood: "음식으로 보관",
        buy: "🛒 구매",
        total: "합계",
        weather: "날씨",
        sunny: "맑음",
        rainy: "비",
        cloudy: "흐림",
        heavyRain: "폭우",
        heatwave: "폭염",
        typhoon: "태풍",
        blizzard: "폭설",
        heavyRainAlertTitle: "폭우 경보!",
        heatwaveAlertTitle: "이례적인 폭염!",
        typhoonAlertTitle: "희귀 태풍 발생!",
        blizzardAlertTitle: "기록적인 폭설!",
        heavyRainAlertBody: "폭우로 인해 농작물 가격이 50% 급등했습니다!",
        heatwaveAlertBody: "뜨거운 날씨로 작물이 더 빨리 자라지만, 배고픔도 빨리 찾아옵니다!",
        typhoonAlertBody: "강한 바람이 일부 농작물을 파괴했습니다!",
        blizzardAlertBody: "눈보라가 몰아쳐 모든 농작물의 성장이 멈췄습니다!",
        disasterChance: "자연재해 확률",
        money: "골드",
        moneyTooltip: "현재 보유한 골드입니다. 씨앗, 음식을 사거나 농장을 확장하는 데 사용됩니다.",
        scoreTooltip: "현재 점수입니다. 농작물을 팔거나 다른 활동을 하면 점수가 오릅니다.",
        weatherTooltip: "현재 날씨입니다. 날씨는 작물과 게임 이벤트에 영향을 줄 수 있습니다.",
        disasterChanceTooltip: "다음 날씨가 변경될 때 자연재해가 발생할 확률입니다.",
        wateringCanTooltip: "물뿌리개를 보유하고 있습니다! 새로 심은 작물에 자동으로 물을 주어 성장 시간을 50% 단축합니다.",
        hungerTooltip: "배고픔 수치입니다 (베타 모드). 음식을 먹어 회복하세요. 0이 되면 페널티를 받게 됩니다.",
        day: "일",
        dayTooltip: "현재 날짜입니다. 매일 새로운 날이 시작될 때 날씨와 시세가 바뀝니다.",
        nextDisasterChanceLabel: "다음 확률",
        pricesRefreshIn: "시세 갱신까지",
        year: "년",
        month: "월",
        spring: "봄",
        summer: "여름",
        autumn: "가을",
        winter: "겨울",
        greenhouse: "비닐하우스",
        greenhouseDescription: "계절에 상관없이 작물을 재배할 수 있습니다. 겨울 농사의 필수품!",
        viewGreenhouse: "🌿 비닐하우스",
        greenhouseSeedShop: "비닐하우스 씨앗 상점",
        expandGreenhouse: "🌿 비닐하우스 확장",
        chooseStartingSeason: "시작할 계절을 선택하세요",
        level: "레벨",
        xp: "경험치",
        achievements: "🏆 업적",
        upgrades: "✨ 개선",
        newAchievementUnlocked: "새로운 업적 달성!",
        achievement_money1_name: "시작이 반",
        achievement_money1_desc: "총 500 골드를 획득하세요.",
        achievement_money2_name: "부유한 농부",
        achievement_money2_desc: "총 5,000 골드를 획득하세요.",
        achievement_money3_name: "골드 수집가",
        achievement_money3_desc: "총 25,000 골드를 획득하세요.",
        achievement_money4_name: "농장 재벌",
        achievement_money4_desc: "총 100,000 골드를 획득하세요.",
        achievement_harvest1_name: "첫 수확",
        achievement_harvest1_desc: "첫 작물을 성공적으로 수확하세요.",
        achievement_harvest2_name: "초록 손가락",
        achievement_harvest2_desc: "총 50개의 작물을 수확하세요.",
        achievement_harvest3_name: "수확 전문가",
        achievement_harvest3_desc: "총 250개의 작물을 수확하세요.",
        achievement_harvest4_name: "대지의 주인",
        achievement_harvest4_desc: "총 1,000개의 작물을 수확하세요.",
        achievement_level1_name: "초보 농부",
        achievement_level1_desc: "레벨 5를 달성하세요.",
        achievement_level2_name: "숙련된 농부",
        achievement_level2_desc: "레벨 10을 달성하세요.",
        achievement_level3_name: "전설적인 농부",
        achievement_level3_desc: "레벨 20을 달성하세요.",
        achievement_expand1_name: "성장의 공간",
        achievement_expand1_desc: "처음으로 농장을 확장하세요.",
        achievement_expand2_name: "지주",
        achievement_expand2_desc: "농장 부지 15개를 소유하세요.",
        achievement_expand3_name: "농업 제국",
        achievement_expand3_desc: "농장 부지 25개를 소유하세요.",
        achievement_greenhouse1_name: "사계절",
        achievement_greenhouse1_desc: "비닐하우스를 건설하세요.",
        achievement_greenhouse2_name: "유리 정원사",
        achievement_greenhouse2_desc: "비닐하우스 부지 10개를 소유하세요.",
        achievement_greenhouse3_name: "통제된 환경",
        achievement_greenhouse3_desc: "비닐하우스 부지 20개를 소유하세요.",
        achievement_seasonalSpring_name: "봄 전문가",
        achievement_seasonalSpring_desc: "봄 작물 25개를 수확하세요.",
        achievement_seasonalSummer_name: "여름 전문가",
        achievement_seasonalSummer_desc: "여름 작물 25개를 수확하세요.",
        achievement_seasonalAutumn_name: "가을 전문가",
        achievement_seasonalAutumn_desc: "가을 작물 25개를 수확하세요.",
        achievement_seasonalWinter_name: "겨울 전문가",
        achievement_seasonalWinter_desc: "겨울에 비닐하우스에서 작물 25개를 수확하세요.",
        achievement_foodie1_name: "미식가",
        achievement_foodie1_desc: "베타 모드에서 음식을 10번 드세요.",
        achievement_foodie2_name: "대식가",
        achievement_foodie2_desc: "베타 모드에서 음식을 50번 드세요.",
        achievement_buildBarn1_name: "목장주인의 시작",
        achievement_buildBarn1_desc: "동물을 위한 목장을 건설하세요.",
        achievement_buyChicken1_name: "첫 친구",
        achievement_buyChicken1_desc: "첫 닭을 구입하세요.",
        achievement_collectEgg1_name: "달걀 수집가",
        achievement_collectEgg1_desc: "첫 달걀을 수집하세요.",
        achievement_buyCow1_name: "얼룩소 친구",
        achievement_buyCow1_desc: "첫 소를 구입하세요.",
        achievement_collectMilk1_name: "신선한 우유",
        achievement_collectMilk1_desc: "첫 우유를 수집하세요.",
        achievement_buyPig1_name: "꿀꿀이 가족",
        achievement_buyPig1_desc: "첫 돼지를 구입하세요.",
        achievement_collectTruffle1_name: "보물 사냥꾼",
        achievement_collectTruffle1_desc: "첫 트러플을 찾아내세요.",
        totalGoldEarned: "총 획득 골드",
        cropsHarvested: "수확한 작물",
        farmPlots: "농장 부지",
        completed: "완료",
        levelUpTitle: "레벨 업!",
        levelUpMessage: "레벨 {level}을 달성했습니다!",
        levelUpReward: "보상:",
        claimReward: "🎁 획득",
        milestoneReward: "단계별 보상",
        claimYourReward: "🎁 보상 받기!",
        achievementsCompleted: "업적 {count} / 5 개 완료",
        allAchievementsCompleted: "모든 업적 완료!",
        comingSoon: "업데이트 예정...",
        milestoneRewardTitle: "엄청난 보상!",
        milestoneRewardMessage: "{count}개의 업적을 완료했습니다! 보상을 드립니다:",
        andSeeds: "그리고 모든 씨앗 {count}개씩!",
        category_Money: "재산",
        category_Harvest: "수확",
        category_Level: "레벨 업",
        category_Expansion: "확장",
        category_Greenhouse: "비닐하우스",
        category_Seasonal: "계절 전문가",
        category_Beta: "베타 테스터",
        category_Husbandry: "목축",
        bulletinBoard: "📌 게시판",
        activeOrder: "진행 중인 주문",
        availableOrders: "가능한 주문",
        accept: "✅ 수락",
        progress: "진행도",
        noOrdersAvailable: "오늘은 새 주문이 없어요.",
        requester_restaurant: "짭짤한 오징어 카페",
        requester_mayor: "촌장님 사무실",
        requester_school: "마을 학교",
        barn: "목장",
        buildBarn: "🏠 목장 짓기",
        buildBarnDescription: "동물들을 위한 집을 마련합니다.",
        visitBarn: "🛖 목장 가기",
        animals: "🐾 동물",
        supplies: "📦 용품",
        animalShop: "동물 상점",
        suppliesShop: "용품 상점",
        chicken: "닭",
        cow: "소",
        pig: "돼지",
        egg: "달걀",
        milk: "우유",
        truffle: "트러플",
        golden_egg: "황금알",
        products: "🥚 생산품",
        feedAllAnimals: "🌾 모든 동물에게 먹이 주기",
        returnToFarm: "🚜 농장으로 돌아가기",
        tradingPost: "⚖️ 거래소",
        barter: "물물교환",
        trade: "🤝 교환",
        sellGoods: "💰 물품 판매",
        kitchen: "🍳 부엌",
        cook: "👨‍🍳 요리하기",
        ingredients: "재료",
        crops: "🥕 농작물",
        moreActions: "🏘️ 마을 활동",
        petShelter: "🐾 펫 보호소",
        adoptAPet: "펫 입양하기",
        adopt: "입양",
        youAdopted: "새로운 친구...",
        great: "좋아요!",
        rarity_common: "일반",
        rarity_rare: "희귀",
        rarity_epic: "영웅",
        rarity_legendary: "전설",
        farm_dog: "농장 강아지",
        farm_dog_desc: "충성스러운 친구. 매일 아침 10% 확률로 1~3개의 동물 먹이를 찾아옵니다.",
        calico_cat: "삼색 고양이",
        calico_cat_desc: "행운을 가져다줍니다. 모든 판매 수익이 5% 증가합니다.",
        wise_owl: "지혜로운 부엉이",
        wise_owl_desc: "현명한 친구. 모든 경험치 획득량이 10% 증가합니다.",
        golden_goose: "황금 거위",
        golden_goose_desc: "특별한 새. 매일 아침 5% 확률로 매우 값비싼 황금알을 낳습니다.",
        mini_dragon: "미니 드래곤",
        mini_dragon_desc: "신화 속 친구. 비옥한 불꽃으로 모든 작물의 성장 시간을 15% 단축시킵니다.",
        petTooltip: "당신의 펫입니다. 클릭해서 펫을 관리하세요.",
        petGacha: "🐾 펫 뽑기",
        petHouse: "🏠 펫 하우스",
        pull1: "1회 뽑기",
        pull10: "10회 뽑기",
        pullCost: "비용: 🦴 {count}",
        guaranteedRare: "희귀 등급 이상 1마리 확정!",
        probabilities: "확률 정보",
        myPets: "나의 펫",
        activeCompanion: "현재 동료",
        setActive: "대표로 설정",
        newFriends: "새로운 친구들!",
        profile: "프로필",
        farmRecord: "농장 기록",
        stat_totalGoldEarned: "총 획득 골드",
        stat_totalCropsHarvested: "총 수확 작물",
        stat_farmPlots: "농장 부지",
        stat_greenhousePlots: "온실 부지",
        stat_hasGreenhouse: "온실 건설됨",
        stat_springCrops: "봄 수확량",
        stat_summerCrops: "여름 수확량",
        stat_autumnCrops: "가을 수확량",
        stat_winterCrops: "겨울 수확량",
        stat_foodEaten: "먹은 음식",
        stat_hasBarn: "목장 건설됨",
        stat_totalAnimals: "총 동물 수",
        stat_totalProductsCollected: "총 생산품 수집",
        willowSleeps: "버드나무가 잠들어 있습니다...",
        listenToWillow: "버드나무의 속삭임 듣기",
        whisperingWillow: "속삭이는 버드나무",
        willowHums: "고대의 나무가 잠재된 에너지로 흥얼거립니다...",
    }
};

export const initialPlots: PlotState[] = Array.from({ length: INITIAL_FARM_SIZE }, () => ({
    crop: null,
    state: 'empty',
    growthStartTime: null,
    isWatered: false,
    isFertilized: false,
}));

export const initialGreenhousePlots: PlotState[] = Array.from({ length: INITIAL_GREENHOUSE_SIZE }, () => ({
    crop: null,
    state: 'empty',
    growthStartTime: null,
    isWatered: false,
    isFertilized: false,
}));

export const getInitialFoodInventory = () => (Object.keys(FOOD_DATA) as FoodType[]).reduce((acc, key) => {
    acc[key] = 0;
    return acc;
}, {} as Record<FoodType, number>);

export const getInitialRawCrops = () => (Object.keys(CROP_DATA) as CropType[]).reduce((acc, key) => {
    acc[key] = 0;
    return acc;
}, {} as Record<CropType, number>);

export const getInitialAnimalProducts = () => (Object.keys(ANIMAL_PRODUCT_DATA) as AnimalProductType[]).reduce((acc, key) => {
    acc[key] = 0;
    return acc;
}, {} as Record<AnimalProductType, number>);

export const getInitialSupplies = () => (Object.keys(SUPPLY_DATA) as SupplyType[]).reduce((acc, key) => {
    acc[key] = 0;
    return acc;
}, {} as Record<SupplyType, number>);


export const getInitialMarketPrices = () => (Object.keys(CROP_DATA) as CropType[]).reduce((acc, key) => {
    acc[key] = 1.0;
    return acc;
}, {} as Record<CropType, number>);